### PR TITLE
Update jquery.maskMonkey.js with upstream fix

### LINKED ISSUE #33: Stopped working after v1.2.2 update with an empty `prefix`
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-money.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/money).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Within an ActiveForm, I put the following simple field:

```php
<?= $form->field($model, 'price')->widget(MaskMoney::classname(), [      
        'pluginOptions' => [                                                    
        'prefix' => '',                                                         
        'suffix' => ' $',                                                          
        'allowNegative' => false                                                
    ]                                                                              
]) ?>                                                                           
```

## Expected behavior and actual behavior

The field behaves bad when I type digits (digits dissappears and so on).

I was expecting to work OK as before.

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-money version: v1.2.2, dev-master

## Isolating the problem

- [x] This bug doesn't happens [on the demos page](https://demos.krajee.com/money) because it doesn't have a demo with an empty prefix.
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-money without other plugins.

### PR DESCRIPTION
**Pull request by ricpelo**
Fixes #33.

## Scope
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made (this change is also documented in the [change log](https://github.com/kartik-v/yii2-money/blob/master/CHANGE.md)):

- Fix regression with empty `prefix`.

## Related Issues

Fixes #33.

### CODE REVIEW

**Comment by kartik-v** [comment]
Thanks. Can you please update the minified JS file as well over the PR.

**Comment by ricpelo** [comment]
Sure. What tool can I use to minimize the JS? Do you recommend me anyone?

**Comment by kartik-v** [comment]
You can do the minification [online from here](http://refresh-sf.com/)

**Comment by ricpelo** [comment]
Thank you very much. I'm going for it.

**Comment by ricpelo** [comment]
Thank you for your great job!

**Pull request merged**
